### ISSUE TITLE
wps pin not found 

### ISSUE THREAD

**Issue by amazer-bil** [kcdtv/tdn#1]
i'm really sorry brother. because i'm new here that's why.i don't know how to discus things.
its because i saw you some comments helping people i thought i'd ask you for help.sorry again :)

**Comment by kcdtv** [comment]
This is a repository for tdn.sh which is about two specific models from Trendnet. 
  It has nothing to do with reaver or pixie dust attack.
I won't help you, and you should be able to find by yourself the answer to your "question" by searching a little and reading.  
  There is an excellent thread started by soxrock2212 in Kali linux forum about pixie dust breach. I recommend you to start by reading it.
  Please do not open any issue here unless it is a bout **tdn.sh** 
 Thanks.
